[[permission]]
identifier = "app-default"
description = """
Allows frontend to invoke only the application-defined Rust commands that the UI relies on.

This is an explicit allowlist to reduce accidental exposure of new commands.
"""

commands.allow = [
  "profiles_list",
  "profile_create",
  "profile_delete",
  "get_active_profile",
  "set_active_profile",
  "login_vault",
  "lock_vault",
  "is_logged_in",
  "health_check",

  "list_attachments",
  "attachments_pick_files",
  "attachments_discard_pick",
  "add_attachments_from_pick",
  "add_attachments_via_dialog",
  "remove_attachment",
  "purge_attachment",
  "get_attachment_bytes_base64",
  "get_attachment_preview",
  "save_attachment_via_dialog",

  "backup_create",
  "backup_restore",
  "backup_inspect",
  "backup_restore_workflow",
  "backup_list",
  "backup_create_if_due_auto",

  "list_folders",
  "create_folder",
  "rename_folder",
  "move_folder",
  "delete_folder_only",
  "delete_folder_and_cards",

  "list_bank_cards_summary_command",
  "list_deleted_bank_cards_summary_command",
  "get_bank_card",
  "create_bank_card",
  "update_bank_card",
  "set_bank_card_favorite",
  "delete_bank_card",
  "restore_bank_card",
  "purge_bank_card",
  "restore_all_deleted_bank_cards",
  "purge_all_deleted_bank_cards",

  "list_datacards",
  "list_datacards_summary_command",
  "get_datacard",
  "create_datacard",
  "update_datacard",
  "set_datacard_favorite",
  "move_datacard_to_folder",
  "delete_datacard",
  "list_deleted_datacards",
  "list_deleted_datacards_summary_command",
  "restore_datacard",
  "purge_datacard",
  "restore_all_deleted_datacards",
  "purge_all_deleted_datacards",

  "get_datacard_password_history",
  "clear_datacard_password_history",

  "get_settings",
  "update_settings",

  "workspace_list",
  "workspace_select",
  "workspace_create",
  "workspace_create_default",
  "workspace_remove",
  "workspace_open_in_explorer",

  "clipboard_clear_all",
]
