[[permission]]
identifier = "app-default"
description = """
Allowlist for app-defined commands used by the UI.
This reduces accidental exposure if new commands are added later.
"""

commands.allow = [
  "profiles_list",
  "profile_create",
  "profile_delete",
  "profile_rename",
  "profile_set_password",
  "profile_change_password",
  "profile_remove_password",
  "get_active_profile",
  "set_active_profile",
  "login_vault",
  "lock_vault",
  "is_logged_in",
  "health_check",

  "list_attachments",
  "attachments_pick_files",
  "attachments_discard_pick",
  "add_attachments_from_pick",
  "add_attachments_via_dialog",
  "remove_attachment",
  "purge_attachment",
  "get_attachment_bytes_base64",
  "get_attachment_preview",
  "save_attachment_via_dialog",

  "backup_create",
  "backup_create_via_dialog",
  "backup_pick_file",
  "backup_discard_pick",
  "backup_restore_workflow_from_pick",
  "backup_list",
  "backup_create_if_due_auto",

  "list_folders",
  "list_vaults",
  "create_vault",
  "set_active_vault",
  "create_folder",
  "rename_folder",
  "move_folder",
  "delete_folder_only",
  "delete_folder_and_cards",

  "list_bank_cards_summary_command",
  "list_deleted_bank_cards_summary_command",
  "get_bank_card",
  "create_bank_card",
  "update_bank_card",
  "set_bank_card_favorite",
  "set_bankcard_archived",
  "search_bank_cards",
  "delete_bank_card",
  "restore_bank_card",
  "purge_bank_card",
  "restore_all_deleted_bank_cards",
  "purge_all_deleted_bank_cards",

  "list_datacards_summary_command",
  "list_deleted_datacards_summary_command",
  "get_datacard",
  "list_datacards",
  "create_datacard",
  "update_datacard",
  "set_datacard_favorite",
  "set_datacard_archived",
  "search_datacards",
  "move_datacard_to_folder",
  "delete_datacard",
  "list_deleted_datacards",
  "restore_datacard",
  "purge_datacard",
  "restore_all_deleted_datacards",
  "purge_all_deleted_datacards",
  "get_datacard_password_history",
  "clear_datacard_password_history",

  "get_settings",
  "update_settings",

  "get_datacard_preview_fields",
  "set_datacard_preview_fields",
  "set_datacard_preview_fields_for_card",
  "get_bankcard_preview_fields",
  "set_bankcard_preview_fields",
  "set_bankcard_preview_fields_for_card",
  "get_datacard_core_hidden_fields",
  "set_datacard_core_hidden_fields",
  "get_bankcard_core_hidden_fields",
  "set_bankcard_core_hidden_fields",

  "workspace_list",
  "workspace_select",
  "workspace_create",
  "workspace_create_via_dialog",
  "workspace_create_default",
  "workspace_remove",
  "workspace_open_in_explorer",

  "clipboard_clear_all",
]
